### ISSUE TITLE
MariaDB Galera Cluster with Network Volumes

### ISSUE THREAD

**Issue by jaschaio** [colinmollenhour/mariadb-galera-swarm#41]
I was able to create a MariaDB Galera Cluster with the example stack file.

But I am concerned that it uses local docker volumes. What happens if a docker swarm node fails and I have to recreate it on a new host? Will the data be copied from the rest of the healthy MariaDB nodes? What happens performance wise if we are talking about very large databases? ( > 200GB and more)

To persist data even if a swarm node fails I am usually using [rexray](https://rexray.readthedocs.io/en/stable/) volumes to attach external block storage to my swarm nodes.

The problem is that I can't scale the MariaDB Cluster across different nodes, as I can only attach the block storage to a single node at a time.

**So this doesn't work:**

```
services:
    
    [… seed service]
  
    node:
        image: colinmollenhour/mariadb-galera-swarm:10.1
        [… networks, environment, secrets, commands etc.]
        volumes:
            - database:/var/lib/mysql
        deploy:
            replicas: 3

volumes:
    database:
        driver: rexray/dobs
```

It would only work if all three replicas would sit on the same docker swarm node which makes no sense as I would have no failover if the swarm node fails for some reason.

Aparently locking doesn't work neither when all mariadb nodes use the exact same volume. (I wasn't able to start the swarm with a single volume).

Another approach could be to create three different `node services` which each use a different rexray volume. But than I don't have the automatic load balancing anymore which docker swarm mode provides when multiple replicas are run of the same services. Is there something I could put in front of MariaDB to load balance the requests?

Or would a shared file system like GlusterFS make sense?

To be honest this is more a best practices question than a bug. I just dont know where to ask for this but feel that this is a very important question that is not well documentated anywhere.

**Comment by jaschaio** [comment]
This might be a solution to the problem:

Its possible to give a unique name to each rexray volume for each replica to use:

```
services:
    
    [… seed service]
  
    node:
        image: colinmollenhour/mariadb-galera-swarm:10.1
        [… networks, environment, secrets, commands etc.]
        volumes:
            - database:/var/lib/mysql
        deploy:
            replicas: 3

volumes:
    database:
        name: '{{.Service.Name}}-{{.Task.Slot}}'
        driver: rexray/dobs
```

After deploying the stack and creating the galera cluster you will get the following if you output `docker volume ls`:

```
rexray/dobs:latest   mysql-node-1
rexray/dobs:latest   mysql-node-2
rexray/dobs:latest   mysql-node-3
rexray/dobs:latest   mysql-seed-1
```
*(The mysql- prefix depends on your stack name)*

Not sure if I am overlooking something but this seems solid.
