### ISSUE TITLE
start.sh: Trapped error on line 120

### ISSUE THREAD

**Issue by ajarmoszuk** [colinmollenhour/mariadb-galera-swarm#59]
Hi all,
I'm getting the following error on one of the nodes as soon as I want to start two after starting the seed: `start.sh: Trapped error on line 120` on the node that doesn't want to start.

Here is my docker-compose.yml file:
version: '3.4'

```
services:
  seed:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - NODE_ADDRESS=^10.0.9.*
    networks:
      - database-net
    command: seed
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager
    secrets:
      - xtrabackup_password
      - mysql_password
      - mysql_root_password
  node:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=^10.0.9.*
      - HEALTHY_WHILE_BOOTING=1
    networks:
      - database-net
    command: node seed,node
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.role == worker
    secrets:
      - xtrabackup_password

volumes:
  mysql-data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'
    driver: local

networks:
  database-net:
    external: true

secrets:
  xtrabackup_password:
    file: .secrets/xtrabackup_password
  mysql_password:
    file: .secrets/mysql_password
  mysql_root_password:
    file: .secrets/mysql_root_password
```

It's exactly the same as the one in the tutorial however I created an external network via overlay on subnet 10.0.9.0/24, it should work, I even tried copying directly from the tutorial and the issue is the same.
