### ISSUE TITLE
Cant set MYSQL_ROOT_HOST

### ISSUE THREAD

**Issue by TheGreatDoc** [colinmollenhour/mariadb-galera-swarm#96]
Hi,

Im trying to set MYSQL_ROOT_HOST but whatever I do it is always set to 127.0.0.1 and I thing its probably related to
https://github.com/colinmollenhour/mariadb-galera-swarm/blob/8a1627360820a1b33cdbae9072a44234b5a49d7d/start.sh#L219

Shouldnt it be `if ! [ -z "$MYSQL_ROOT_HOST" ]; then` ?

So only if `MYSQL_ROOT_HOST` is empty it will be 127.0.0.1

**Comment by colinmollenhour** [comment]
The `-z` test is true if the string is zero length so I think that line is correct. Are you sure the environment variable is passing through properly?

**Comment by csib** [comment]
@TheGreatDoc 
Use it like this, it is works for me:
```
version: '3.4'

services:
  seed:
    image: colinmollenhour/mariadb-galera-swarm:10.4.11-2020-01-06
    environment:
[...]
      - MYSQL_ROOT_HOST=%
      - DEFAULT_TIME_ZONE=Europe/Budapest
      - NODE_ADDRESS=^10.0.*.*
    networks:
      - db_network
    command: seed
    volumes:
      - mysql-data:/var/lib/mysql
```
